trigger message api
thecodingmachine/workadventure pull request #1022
Opened 2021-05-10 16:11 UTC by jonnytest1

allow triggering of custom triggerMessage

2021-05-10 16:36 UTC, jonnytest1 commented
@moufmouf

2021-05-25 11:55 UTC, jonnytest1 commented
@moufmouf @gparant how about it ?

2021-05-26 13:47 UTC, moufmouf requested changes
Hey @jonnytest1 ,

Pretty cool.
I'm OK to add this feature to the scripting API, it makes sense.

Also, rather than returning a "string" that can be used to remove the message with `removeTriggerMessage`, I think we should do as we did with Popups: return an object that has a class method:

```
triggerMessage(message:string, callback:() => void): TriggerMessage

class TriggerMessage {
    close(): void;
}
```

Finally, could you add the relevant documentation is the doc? In `docs/maps/api-reference.md`.

Thanks a lot and sorry to take so long to review your PR!

2021-05-26 16:10 UTC, jonnytest1 commented on maps/tests/script.js
> +///<reference path="../../front/src/iframe_api.ts" />
@moufmouf  this allows type checking in javascript files if checkJs is enabled in tsConfig

2021-05-26 16:13 UTC, jonnytest1 commented on front/src/iframe_api.ts
> +    triggerMessage(message: string, callback: () => void): {
i was thinking about extracting it into a class  but honestly i would jsut rather move it to its own file completely 
like described in here

2021-06-23 15:03 UTC, closed without merging