fix for https://github.com/thecodingmachine/workadventure/issues/1256
thecodingmachine/workadventure pull request #1260
Opened 2021-07-02 17:15 UTC by jonnytest1

2021-07-02 17:20 UTC, jonnytest1 commented
@moufmouf

2021-09-01 15:57 UTC, Kharhamel commented
Hello, thanks for the PR. Could you fix the conflicts and remove the changes to the linters from this PR? I will merge this once this is done.

2021-09-02 15:16 UTC, Kharhamel requested changes

2021-09-02 15:16 UTC, Kharhamel commented on front/.eslintrc.json
> +        "quotes": [
please don't change this file in a "fix" PR

2021-09-02 15:16 UTC, Kharhamel commented on front/.prettierrc.json
> -  "printWidth": 120,
please don't change this file in a "fix" PR

2021-12-20 18:47 UTC, Chasethechicken commented
Hey @jonnytest1, sorry for pinging you, but PR this would be really useful.
Are you still planning on fixing it, or would you prefer if somebody else tackled #1256?

2021-12-21 02:10 UTC, jonnytest1 commented
> Hey @jonnytest1, sorry for pinging you, but PR this would be really useful.
> Are you still planning on fixing it, or would you prefer if somebody else tackled #1256?

Feel free to do it yourself :) I'm currently on vacation anyways ^^ 
PS u can probably just remove the questionable linter changes and re-request it 
😅

2021-12-23 13:29 UTC, closed without merging