Add min browser version error
thecodingmachine/workadventure pull request #1726
Opened 2022-01-13 16:28 UTC by nolway

Add min version supported : 
Firefox : 80
Chrome: 80
Opera : 70
Safrari: 13

![Screenshot from 2022-01-13 17-15-00](https://user-images.githubusercontent.com/3711182/149369418-55830a18-b8d1-4d44-8865-5cf645aacbad.png)

2022-01-13 17:12 UTC, moufmouf commented on front/src/Utils/BrowserUtils.ts
> +            name: "safrari",
`safari` ? :D

2022-01-13 17:17 UTC, moufmouf requested changes
Just a small typo in the "safari" word.

Also, as an alternative to displaying a big error page, we already have a place in the application where we display error message for old browsers. Previously, we only checked that the WebRTC API was available, but we could require a more recent version here.

Check out `front/src/Stores/Errors/BrowserTooOldError.ts`

2022-01-26 07:47 UTC, gparant commented on front/src/Utils/BrowserUtils.ts
> +        return !foundBrowser || foundBrowser.minVersion <= currentBrowser.version;
Why do you not searh `minVersion` directly in the find and `return foundBrowser !== null`?

2022-01-26 07:47 UTC, gparant commented on front/src/Utils/BrowserUtils.ts
> +            const matchVersion = userAgent.match(/\bOPR\/(\d+)/);
Could you not create one regex to catch `userAgent` and `version`?

2022-04-21 15:07 UTC, closed without merging