Pet collection integration
thecodingmachine/workadventure pull request #3226
Opened 2023-05-04 15:35 UTC by mlima95

[ADD] - Pet collections to select companion scene

2023-05-10 07:29 UTC, moufmouf requested changes
One thing seems broken. When I come back to the select companion scene after selecting a companion, the view does not open on the companion I selected. It selects the first companion of the list by default.

2023-05-12 16:26 UTC, mlima95 commented
> One thing seems broken. When I come back to the select companion scene after selecting a companion, the view does not open on the companion I selected. It selects the first companion of the list by default.
@moufmouf -> cc69bebb02d8d38b8614437c35f4635d6da021a3 f6e82fbe3715fc09c7cfd5b6b8b7ee24e52b38d2

2023-05-16 07:19 UTC, moufmouf commented on play/src/front/Components/SelectCompanion/SelectCompanionScene.svelte
> +    console.log(selectedCollection);
```suggestion
```

2023-05-16 07:21 UTC, moufmouf commented on play/src/pusher/services/QueryValidator.ts
> +    const params: any = {};
Can we try this?

```suggestion
    const params: Record<string, string|string[]> = {};
```

2023-05-17 08:04 UTC, moufmouf approved these changes

2023-05-17 08:05 UTC, merged