add environment variable to select chat type
thecodingmachine/workadventure pull request #4032
Opened 2024-06-27 15:12 UTC by ydiarra

2024-06-28 16:48 UTC, moufmouf requested changes
Don't forget to update:

- The configuration in contrib/docker
- The configuration in contrib/helm
- Documentation about self-hosting

2024-06-28 16:48 UTC, moufmouf commented on play/src/pusher/enums/EnvironmentVariableValidator.ts
> +    CHAT_TYPE: z.union([z.literal("PROXIMITY"), z.literal("MATRIX")]).default("PROXIMITY"),
If we use an env var to switch between one chat type and the other, we could use a discriminating union.

This way, if `CHAT_TYPE = "MATRIX"`, then all the matrix parameters would be compulsory and not optional?

2024-07-08 14:46 UTC, gparant commented on play/src/pusher/enums/EnvironmentVariableValidator.ts
> +            MATRIX_DOMAIN: z.undefined(),
A supprimer pour le type "CHAT_TYPE"

2024-07-08 14:51 UTC, gparant commented on contrib/helm/values.yaml
> +    MATRIX_ADMIN_USER:
Add `""`

2025-12-01 16:57 UTC, closed without merging