Input need camera and microphone permission
thecodingmachine/workadventure pull request #700
Opened 2021-02-02 16:34 UTC by gparant

Create input of camera and microphone permission

![Capture d’écran 2021-02-02 à 17 31 37](https://user-images.githubusercontent.com/23724509/106631151-c3c8d100-657c-11eb-9bd9-478f2055ac3f.png)

2021-02-03 16:49 UTC, gparant commented
- [ ] Add firefox image 
- [ ] The check in the game and possibility to continue in the game without permissions.

2021-03-19 13:57 UTC, moufmouf requested changes

2021-03-19 13:57 UTC, moufmouf commented on front/dist/resources/html/helpCameraSettings.html
> +        <h5>Need Audio Video Inputs</h5>
```suggestion
        <h5>Camera/Microphone access needed</h5>
```

2021-03-19 13:57 UTC, moufmouf commented on front/src/Phaser/Game/GameScene.ts
> +
We should move this in a separate private function that we call here.

2021-03-19 13:57 UTC, moufmouf commented on front/src/Phaser/Game/GameScene.ts
> +        if(!this.helpCameraSettingsOpened) {
Remove this because it prevents showing other players moving, etc...

2021-03-19 13:57 UTC, moufmouf commented on front/src/Phaser/Game/GameScene.ts
> +    private helpCameraSettingsOpened: boolean = false; //#700
We should move all this code in a complete separate Scene.

- Create the new class (copy paste from MenuScene)
- Reference the new scene in index.ts
- Start the new scene when the menuScene is started

2021-03-19 13:57 UTC, moufmouf commented on front/src/Phaser/Game/GameScene.ts
> +            x: this.startX - (400/2),
The menu position should be relative to the window width only.

2021-03-19 13:57 UTC, moufmouf commented on front/src/Phaser/Login/EnableCameraScene.ts
> +    private reset(){
Remove this, it is not called anywhere

2021-03-19 15:17 UTC, moufmouf commented on front/src/Phaser/Game/GameScene.ts
> +import {tryCatch} from "rxjs/internal-compatibility";
Is this used somewhere?

2021-03-19 16:09 UTC, merged