WIP: FEATURE: complete control over the iframe size
thecodingmachine/workadventure pull request #816
Opened 2021-03-15 17:43 UTC by Kharhamel

2021-03-17 19:20 UTC, moufmouf requested changes
Pretty cool, but there is one issue:

It is breaking the responsiveness. On vertical displays, the iframe is broken and cannot be resized.

2021-03-18 14:06 UTC, Kharhamel commented
@moufmouf this is fixed now.

2021-03-18 15:13 UTC, moufmouf approved these changes

2021-03-18 15:16 UTC, merged

2021-03-19 14:45 UTC, fbartels commented
There seems to be another issue with this feature. When opening the iframe now Jitsi only uses half of the available size of the iframe. Only when removing https://github.com/thecodingmachine/workadventure/blob/1f85e548ce137a2db5a33588b72ae559ea390643/front/dist/resources/style/cowebsite.scss#L115 in the debugger jitsi will fill the full iframe.

![image](https://user-images.githubusercontent.com/1257835/111797851-cdf32480-88c9-11eb-8899-a2e77c397630.png)