Replaced the hard-coded URLs by variables
thecodingmachine/workadventure pull request #840
Opened 2021-03-24 23:17 UTC by ValdoTR

Replace all the hard-coded URLs from the docker-compose file with env variables.
Add also one doc instruction about creating the env file needed by docker-compose.

2021-03-25 15:41 UTC, tabascoeye requested changes
looks nice, but UPLOADER should be PUSHER in a few places

2021-03-25 15:41 UTC, tabascoeye commented on .env.template
> +UPLOADER_SUBDOMAIN=pusher
should be PUSHER_SUBDOMAIN

2021-03-25 15:41 UTC, tabascoeye commented on docker-compose.yaml
> +      API_URL: $UPLOADER_SUBDOMAIN.$DOMAIN
should be $PUSHER_SUBDOMAIN.$DOMAIN

2021-03-25 15:41 UTC, tabascoeye commented on docker-compose.yaml
> +      - "traefik.http.routers.pusher.rule=Host(`$UPLOADER_SUBDOMAIN.$DOMAIN`)"
should be PUSHER_SUBDOMAIN

2021-03-25 15:41 UTC, tabascoeye commented on docker-compose.yaml
> +      - "traefik.http.routers.pusher-ssl.rule=Host(`$UPLOADER_SUBDOMAIN.$DOMAIN`)"
should be PUSHER_SUBDOMAIN

2021-03-26 13:41 UTC, ValdoTR commented
Thank you @tabascoeye ! just a copy/past issue ;)
Will fix this.

2021-06-29 10:13 UTC, ValdoTR commented
I'm canceling thit because after thinking it, I don't think it really helps to allow the user to configure domains and subdomains, it might even mislead him.

2021-06-29 10:13 UTC, closed without merging